services:
  coklit-fe:
    container_name: coklit-fe
    image: coklit-fe:latest
    build: .
    env_file:
      - .env.production
    entrypoint: 
      - node
      - server.js
    network_mode: host